# Generated by Django 3.0.4 on 2020-04-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='customer',
            field=models.IntegerField(),
        ),
    ]
