# Generated by Django 3.0.4 on 2020-04-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200412_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='customer',
            field=models.CharField(max_length=150),
        ),
    ]
