# Generated by Django 3.0.4 on 2020-04-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200326_1512'),
        ('transactions', '0003_auto_20200412_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
