# Generated by Django 3.0.4 on 2020-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200413_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cashIn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='cashOut',
            field=models.CharField(max_length=200),
        ),
    ]
