# Generated by Django 3.0.4 on 2020-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='idNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobileNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uniqueID',
            field=models.IntegerField(),
        ),
    ]
