# Generated by Django 3.0.4 on 2020-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200326_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobileNo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(max_length=5),
        ),
    ]
