# Generated by Django 3.0.4 on 2020-03-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_currency_customer_id'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
        ),
    ]
