# Generated by Django 3.0.4 on 2020-03-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='customer_id',
        ),
    ]
